language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pycrypto
  - pip install pytest

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - python app